name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    uses: ericz-home/home-ops/.github/workflows/build_publish.yml@main
    with:
      image: ${{ github.repository }}
    secrets: inherit
